name: deontdekfabriek
description: De Ontdek Fabriek app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sensors_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ToiletImage/Bananapeel.png
    - assets/ToiletImage/Compost.png
    - assets/ToiletImage/Leafe.png
    - assets/ToiletImage/Sawdust.png
    - assets/ToiletImage/Sigaret.png
    - assets/ToiletImage/Chewingum.png
    - assets/ToiletImage/Bucket.png
